# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Colossus Innovation LLC
email: info@colossusinnovation.com
description:
  Colossus Innovation specializes in transforming how organizations handle massive
  scale and technical complexity. I bring proven solutions to your toughest 
  challenges. Whether you need to modularize a monolith, implement back-pressure 
  systems to handle massive scale, optimize 6-and-7 figure infrastructure costs, or
  require expert code review for patent litigation, I deliver the technical 
  depth that comes from actually building and debugging systems at global 
  scale.

tagline: Ironclad Solutions for Colossal Ideas
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://colossusinnovation.com" # the base hostname & protocol for your site
permalink: /blog/:year/:month/:day/:title:output_ext

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
markdown: kramdown
